version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    target-branch: updates/dependencies
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      python-prod:
        applies-to: version-updates
        dependency-type: "production"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      python-dev:
        applies-to: version-updates
        dependency-type: "development"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    target-branch: updates/dependencies
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    target-branch: updates/dependencies
    commit-message:
      prefix: "deps"
      include: "scope"
