repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check
        entry: task lint
        language: system
        pass_filenames: false
        always_run: true

      - id: ruff-format
        name: Ruff format
        entry: task format
        language: system
        pass_filenames: false
        always_run: true

      - id: pyright
        name: Pyright
        entry: task typecheck
        language: system
        pass_filenames: false
        always_run: true

      - id: yamllint
        name: Yamllint
        entry: task yamllint
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest
        name: Pytest (unit)
        entry: task test
        language: system
        pass_filenames: false
        always_run: true
